// vite.config.js
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwind from '@tailwindcss/vite'
import { VitePWA } from 'vite-plugin-pwa'

// Toggle PWA in dev only when you actually want it
const enablePWADev = process.env.VITE_PWA_DEV === 'true'

// Try to load the assets generator plugin from either export style.
// If it's not installed or can't be resolved, build still works.
async function loadPwaAssetsPlugin() {
  try {
    // some versions export from the package root
    const mod = await import('@vite-pwa/assets-generator')
    const fn =
      mod.pwaAssets || // named
      mod.default ||   // default
      null
    if (!fn) return []
    return [
      fn({
        image: 'public/icon.svg', // source icon
        preset: {
          transparent: true,
          sizes: [192, 512],
          maskable: { sizes: [192, 512] },
          apple: true,
          favicon: true
        }
      })
    ]
  } catch {
    // not installed / not resolvable: just skip silently
    return []
  }
}

export default defineConfig(async () => {
  const assetsPlugins = await loadPwaAssetsPlugin()

  return {
    base: './',
    plugins: [
      tailwind(),
      react(),
      VitePWA({
        registerType: 'autoUpdate',
        devOptions: { enabled: enablePWADev, navigateFallback: 'index.html' },
        includeAssets: ['favicon.svg', 'robots.txt'],
        manifest: {
          name: 'Checker Calendar',
          short_name: 'Checker',
          start_url: '.',
          scope: '.',
          display: 'standalone',
          background_color: '#0a0a0a',
          theme_color: '#0a0a0a',
          // These PNGs will be generated by the plugin above (or you can place them manually in /public)
          icons: [
            { src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' },
            { src: 'pwa-512x512.png', sizes: '512x512', type: 'image/png' },
            { src: 'maskable-192x192.png', sizes: '192x192', type: 'image/png', purpose: 'maskable' },
            { src: 'maskable-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' }
          ]
        }
      }),
      ...assetsPlugins
    ]
  }
})
